language: python

python:
  - "2.7"
  
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
#script: nosetests

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame
#install:
#    - pip install -r .travis_requirements.txt

script: 
  - python hello_test.py
  - python Game.py

virtualenv:
    system_site_packages: true
